Repository RedHatInsights/insights-core, pull requests merged in 2018-04, with the labels that each got.

#1086 NFS exports combiner and parser improvements
  docs/shared_combiners_catalog/nfs_exports.rst
  insights/combiners/nfs_exports.py
  insights/combiners/tests/test_nfs_exports.py
  insights/parsers/nfs_exports.py
  insights/parsers/tests/test_nfs_exports.py
Labels: 3.x, documentation, enhancement

#1111 Add pcs_status spec. #1082.
  insights/specs/sos_archive.py
Labels: 3.x, bug

#1112 Ease hostname restrictions by filtering blank lines. Fix #1055.
  insights/parsers/hostname.py
  insights/parsers/tests/test_hostname.py
  insights/tests/__init__.py
Labels: 3.x, enhancement

#1106 Samba config documentation
  docs/shared_parsers_catalog/samba.rst
  insights/parsers/samba.py
  insights/parsers/tests/test_samba.py
Labels: 3.x, documentation

#1107 Parser doc heading fixes
  insights/parsers/fstab.py
  insights/parsers/installed_rpms.py
  insights/parsers/ipaupgrade_log.py
  insights/parsers/jboss_domain_log.py
  insights/parsers/libkeyutils.py
  insights/parsers/nginx_conf.py
  insights/parsers/ntp_sources.py
  insights/parsers/smbstatus.py
  insights/parsers/tomcat_xml.py
Labels: 3.x, documentation
