Repository RedHatInsights/insights-core, pull requests merged in 2018-02, with the labels that each got.

#939 Add foreman-rake db:migrate:status parser for 1.x branch
  docs/shared_parsers_catalog/foreman_rake_db_migrate_status.rst
  insights/config/specs.py
  insights/parsers/foreman_rake_db_migrate_status.py
  insights/parsers/tests/test_foreman_rake_db_migrate_status.py
Labels: 1.x, documentation, enhancement

#942 Add foreman-rake db:migrate:status parser for master branch
  docs/shared_parsers_catalog/foreman_rake_db_migrate_status.rst
  insights/parsers/foreman_rake_db_migrate_status.py
  insights/parsers/tests/test_foreman_rake_db_migrate_status.py
  insights/specs.py
  insights/specs_default.py
  insights/specs_insights_archive.py
Labels: 3.x, enhancement, parser

#910 FileListing class to handle single directory listings for 1.x branch
  insights/core/__init__.py
  insights/tests/test_file_listing.py
Labels: 1.x, bug, enhancement

#917 FileListing class to handle single directory listings for master branch
  insights/core/__init__.py
  insights/tests/test_file_listing.py
Labels: 3.x, bug, enhancement

#943 Improve documents of ps.py
  insights/parsers/ps.py
  insights/parsers/tests/test_ps.py
Labels: 3.x

#918 VDSM version 3 & 4 log file parser
  insights/parsers/tests/test_vdsm_log.py
  insights/parsers/vdsm_log.py
Labels: 1.x

#945 Mark 'get_multipath_v4_ll' as deprecated
  insights/parsers/multipath_v4_ll.py
Labels: 1.x

#946 Mark 'get_multipath_v4_ll' as deprecated (3.x)
  insights/parsers/multipath_v4_ll.py
  insights/parsers/tests/test_multipath_v4_ll.py
Labels: 3.x

#950 Pulp worker defaults 1.x
  docs/shared_parsers_catalog/pulp_worker_defaults.rst
  insights/config/specs.py
  insights/parsers/pulp_worker_defaults.py
  insights/parsers/tests/test_pulp_worker_defaults.py
Labels: 1.x

#954 Pulp worker defaults for master branch
  docs/shared_parsers_catalog/pulp_worker_defaults.rst
  insights/parsers/pulp_worker_defaults.py
  insights/parsers/tests/test_pulp_worker_defaults.py
  insights/specs/__init__.py
  insights/specs/default.py
Labels: 3.x

#964 Backport changes from master branch to redhat_release
  insights/parsers/redhat_release.py
  insights/parsers/tests/test_redhat_release.py
Labels: 1.x
