Repository RedHatInsights/insights-core, pull requests merged in 2019-03, with the labels that each got.

#1716 Add parser for ironic-inspector.log
  docs/shared_parsers_catalog/ironic_inspector_log.rst
  insights/parsers/ironic_inspector_log.py
  insights/parsers/tests/test_ironic_inspector_log.py
  insights/specs/__init__.py
  insights/specs/default.py
Labels: FILTER Change, SPEC Change

#1673 Add LC_ALL and LANG to default environment when running commands
  insights/collect.py
  insights/core/spec_factory.py
Labels: 3.x, enhancement

#1721 Let cat use colorama but fall back to regular text if its not installed.
  insights/tools/cat.py
Labels: 3.x, bug

#1720 rule CONTENT was rendering for skipped rules when passing -m/--missing
  insights/formats/__init__.py
  insights/plugins/never_fires.py
Labels: 3.x, bug

#1719 Add filterable option to IronicInspectorLog
  insights/specs/__init__.py
Labels: enhancement

#1728 Provide common base class for our plugin types
  insights/core/plugins.py
Labels: 3.x

#1730 Canonical fact fix
  insights/client/connection.py
  insights/tests/client/test_platform.py
Labels: client

#1703 Add new spec in qemu_xml parser
  insights/parsers/qemu_xml.py
  insights/parsers/tests/test_qemu_xml.py
  insights/specs/__init__.py
  insights/specs/sos_archive.py
Labels: enhancement

#1632 Parser to collect file metadata from `/rhev/data-center` on the RHEV Host
  docs/shared_parsers_catalog/rhev_data_center.rst
  insights/parsers/rhev_data_center.py
  insights/parsers/tests/test_rhev_data_center.py
Labels: FILTER Change, SPEC Change

#1733 Parser for command 'ovs-vsctl list bridge'
  docs/shared_parsers_catalog/ovs_vsctl_list_bridge.rst
  insights/parsers/ovs_vsctl_list_bridge.py
  insights/parsers/tests/test_ovs_vsctl_list_bridge.py
  insights/specs/__init__.py
  insights/specs/default.py
Labels: SPEC Change

#1743 New parser for teamdctl_config_dump
  docs/shared_parsers_catalog/teamdctl_config_dump.rst
  insights/parsers/teamdctl_config_dump.py
  insights/parsers/tests/test_teamdctl_config_dump.py
  insights/specs/__init__.py
  insights/specs/default.py
Labels: SPEC Change

#1742 New parser Sat5InsightsProperties
  docs/shared_parsers_catalog/sat5_insights_properties.rst
  insights/parsers/sat5_insights_properties.py
  insights/parsers/tests/test_sat5_insights_properties.py
  insights/specs/__init__.py
  insights/specs/default.py
Labels: SPEC Change

#1754 [DateUTC] Fix typo in the command
  insights/parsers/date.py
Labels: documentation

#1753 Change sapcontrol to use foreach_execute
  insights/parsers/sapcontrol.py
  insights/parsers/tests/test_sapcontrol.py
  insights/specs/default.py
Labels: SPEC Change

#1745 Parser for parsing command 'ip netns exec <namespace> lsof i'
  docs/shared_parsers_catalog/ip_netns_exec_namespace_lsof.rst
  insights/parsers/ip_netns_exec_namespace_lsof.py
  insights/parsers/tests/test_ip_netns_exec_namespace_lsof.py
  insights/specs/__init__.py
  insights/specs/default.py
Labels: FILTER Change

#1744 Parser for parsing file dhcp_agent.ini
  docs/shared_parsers_catalog/neutron_dhcp_agent_conf.rst
  insights/parsers/neutron_dhcp_agent_conf.py
  insights/parsers/tests/test_neutron_dhcp_agent_conf.py
  insights/specs/__init__.py
  insights/specs/default.py
Labels: FILTER Change, SPEC Change

#1732 Parser and Datasource for ovs_bridge_mac_table_entry_count
  docs/shared_parsers_catalog/ovs_appctl_fdb_show_bridge.rst
  insights/parsers/ovs_appctl_fdb_show_bridge.py
  insights/parsers/tests/test_ovs_appctl_fdb_show_bridge.py
  insights/specs/__init__.py
  insights/specs/default.py
  insights/specs/insights_archive.py
Labels: SPEC Change
