Repository RedHatInsights/insights-core, pull requests merged in 2019-02, with the labels that each got.

#1667 Fix ceph version - add 'downstream_release' field
  insights/parsers/ceph_version.py
  insights/parsers/tests/test_ceph_version.py
Labels: api change, bug

#1669 Some tests were leaving files in /tmp
  insights/tests/client/test_utilities.py
  insights/tests/test_fs.py
Labels: 3.x

#1450 Add parser for 'ceph insights' command
  docs/shared_parsers_catalog/ceph_insights.rst
  insights/core/__init__.py
  insights/parsers/ceph_insights.py
  insights/parsers/tests/test_ceph_insights.py
  insights/specs/__init__.py
  insights/specs/default.py
  insights/specs/insights_archive.py
Labels: SPEC Change

#1679 Rhev data center ds
  insights/core/spec_factory.py
  insights/parsers/tests/test_gluster_vol.py
  insights/specs/__init__.py
  insights/specs/default.py
  insights/specs/insights_archive.py
  insights/tests/test_specs.py
  insights/tools/cat.py
Labels: 3.x, enhancement

#1681 Add Ceph version from RHOSP 10 environment
  insights/parsers/ceph_version.py
  insights/parsers/tests/test_ceph_version.py
Labels: enhancement
