Repository RedHatInsights/insights-core, pull requests merged in 2021-04, with the labels that each got.

#2865 fix(ultralight checkins): wrap thrown exception with catch
  insights/client/phase/v1.py
Labels: client

#3031 Collect /usr/libexec/greenboot/greenboot-status
  docs/shared_parsers_catalog/greenboot_status.rst
  insights/parsers/greenboot_status.py
  insights/parsers/tests/test_greenboot_status.py
  insights/specs/__init__.py
  insights/specs/default.py
Labels: core

#3043 Fix ValueError exception in dmsetup parser
  insights/parsers/dmsetup.py
  insights/parsers/tests/test_dmsetup.py
Labels: bug

#3041 Fix ValueError exception in systemd_analyze parser
  insights/parsers/systemd_analyze.py
  insights/parsers/tests/test_systemd_analyze.py
Labels: bug
