Repository RedHatInsights/insights-core, pull requests merged in 2021-01, with the labels that each got.

#2867 Update Compliance error message
  insights/client/apps/compliance/__init__.py
Labels: client

#2879 Fix error with ipython and jedi in inspect
  setup.py
Labels: bug

#2891 Ensure that args to get_running_commands is a list
  insights/specs/default.py
  insights/tests/test_specs.py
Labels: bug

#2890 Bind first_file to HostArchiveContext in insights_archive.py
  insights/specs/insights_archive.py
Labels: core

#2868 Fix HTTP_PROXY warning condition
  insights/client/config.py
  insights/tests/client/test_config.py
Labels: client

#2893 Add several useful features to parsr.query.
  insights/ocp.py
  insights/parsr/query/__init__.py
  insights/parsr/query/tests/test_choose.py
  insights/parsr/query/tests/test_crumbs.py
Labels: core

#2907 set_enabled works on components and their fully qualified names.
  insights/core/dr.py
  insights/tests/test_dr_enabled.py
Labels: core
