Repository RedHatInsights/insights-core, pull requests merged in 2024-12, with the labels that each got.

#4295 fix: change sysconfig specs as filterable=True
  insights/parsers/sysconfig.py
  insights/specs/__init__.py
  insights/specs/default.py
Labels: BREAK Rules

#4194 chore: Improve and simplify logging
  insights/client/__init__.py
  insights/client/connection.py
  insights/client/phase/v1.py
  insights/tests/client/connection/test_checkin.py
Labels: client

#4266 feat: download egg as per the RHEL major version
  insights/client/__init__.py
Labels: WIP

#4315 feat: Use caplog to test log messages
  .github/workflows/main.yml
  insights/tests/client/connection/test_test_connection.py
  insights/tests/client/init/test_write_pidfile.py
  setup.py
Labels: RHEL 6

#4299 feat: support line filter in spec Cleaner
  insights/core/filters.py
  insights/core/spec_cleaner.py
  insights/core/spec_factory.py
  insights/tests/core/test_component_metadata.py
  insights/tests/core/test_context.py
  insights/tests/core/test_determine_components.py
  insights/tests/core/test_dr_enabled.py
  insights/tests/core/test_dr_run.py
  insights/tests/core/test_evaluators.py
  insights/tests/core/test_extractors.py
  insights/tests/core/test_filters.py
  insights/tests/core/test_get_dependency_specs.py
  insights/tests/core/test_scannable.py
  insights/tests/core/test_serde.py
  insights/tests/core/test_spec_serialization.py
  insights/tests/plugins/__init__.py
  insights/tests/plugins/test_insights_heartbeat.py
  insights/tests/plugins/test_plugin.py
  insights/tests/plugins/test_returns_none.py
  insights/tests/plugins/test_rules_fixture.py
  insights/tests/plugins/test_vulnerable_kernel.py
  insights/tests/plugins/tina_loves_butts.py
  insights/tests/specs/__init__.py
  insights/tests/specs/test_specs.py
  insights/tests/specs/test_specs_content_redaction_empty.py
  insights/tests/specs/test_specs_filters.py
  insights/tests/specs/test_specs_runtime_ds_obfuscation.py
  insights/tests/specs/test_specs_save_as.py
  insights/tests/specs/test_specs_special_content.py
Labels: QE, WIP

#4319 fix: do not print collection messages for compliance apiv2 options
  insights/client/client.py
  insights/tests/client/test_log_messages.py
Labels: QE
