Repository RedHatInsights/insights-core, pull requests merged in 2025-09, with the labels that each got.

#4533 chore: update RPM building scripts and spec file
  build_core_rpm.sh
  insights-core.spec
Labels: RPM

#4540 chore: sync the changelog with the 3.0 branch
  CHANGELOG.md
  insights-core.spec
  insights/RELEASE
  insights/VERSION
Labels: RPM

#4544 fix(client): Suppress link message after upload
  insights/client/phase/v2.py
Labels: client, RPM

#4542 feat: onboard packit for building RPM on master branch
  .packit.yaml
Labels: RPM

#4545 doc: add RPM delivery notes to CONTRIBUTING
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation, CORE

#4566 chore(doc): update the guide steps for PR to 3.0_egg
  CONTRIBUTING.md
Labels: CORE

#4567 chore(doc): update the guide steps for PR to 3.0_egg
  CONTRIBUTING.md
Labels: EGG

#4565 fix(doc): add required configuration for readthedocs
  .readthedocs.yaml
Labels: CORE

#4562 feat: New parser MdatpManaged and the spec
  docs/shared_parsers_catalog/mdatp_managed.rst
  insights/parsers/mdatp_managed.py
  insights/specs/__init__.py
  insights/specs/default.py
  insights/tests/parsers/test_mdatp_managed.py
Labels: CORE, data collection, data processing

#4569 feat: New parser MdatpManaged and the spec
  docs/shared_parsers_catalog/mdatp_managed.rst
  insights/parsers/mdatp_managed.py
  insights/specs/__init__.py
  insights/specs/default.py
  insights/tests/parsers/test_mdatp_managed.py
Labels: EGG

#4546 fix(parser/sshd_config): keep inline comments when parsing config lines
  insights/parsers/ssh.py
  insights/tests/parsers/test_ssh.py
Labels: CORE, data processing

#4570 fix(parser/sshd_config): keep inline comments when parsing config lines
  insights/parsers/ssh.py
  insights/tests/parsers/test_ssh.py
Labels: EGG

#4572 fix(ver): don't use package RELEASE for RPM version up
  .tito/packages/insights-core
  CHANGELOG.md
  insights-core.spec
  insights/RELEASE
  insights/VERSION
Labels: RPM

#4437 fix: no valid conf found issue in combiner GrubConf
  insights/combiners/grub_conf.py
  insights/combiners/grubby.py
  insights/parsers/__init__.py
  insights/parsers/grub_conf.py
  insights/parsers/grubby.py
  insights/tests/__init__.py
  insights/tests/combiners/test_grub_conf.py
  insights/tests/combiners/test_grubby.py
  insights/tests/combiners/test_selinux.py
  insights/tests/parsers/test_grub_conf_efi.py
  insights/tests/parsers/test_grubby.py
Labels: CORE, data processing

#4557 fix(test): regression issue of yaml.SafeLoader in rule testing
  insights/tests/__init__.py
  insights/tests/test_yaml_parser.py
Labels: CORE

#4563 fix(test): regression issue of yaml.SafeLoader in rule testing
  insights/tests/__init__.py
  insights/tests/test_yaml_parser.py
Labels: EGG

#4497 New parser for sos_commands/crio/crictl_ps
  docs/shared_parsers_catalog/crictl_ps.rst
  insights/parsers/crictl_ps.py
  insights/specs/__init__.py
  insights/specs/sos_archive.py
  insights/tests/parsers/test_crictl_ps.py
Labels: CORE, data processing

#4576 New parser for sos_commands/crio/crictl_ps (#4497)
  docs/shared_parsers_catalog/crictl_ps.rst
  insights/parsers/crictl_ps.py
  insights/specs/__init__.py
  insights/specs/sos_archive.py
  insights/tests/parsers/test_crictl_ps.py
Labels: EGG

#4579 chore(ci/cd): build Egg for PRs to 3.0_egg only
  .github/workflows/build_egg.yml
Labels: EGG

#4577 chore: remove the unused build scripts
  build.sh
  build_client_egg.sh
Labels: RPM

#4581 fix: add dep ds containers_with_shell for container specs
  insights/core/spec_factory.py
  insights/specs/datasources/container/__init__.py
  insights/tests/datasources/container/test_nginx_conf.py
  insights/tests/datasources/container/test_running_rhel_containers.py
Labels: CORE, data collection, RPM

#4574 fix: Enhance spec 'filefrag' to check initramfs/vmlinuz files
  insights/specs/default.py
Labels: data collection, RPM

#4582 fix: Enhance spec 'filefrag' to check initramfs/vmlinuz files
  insights/specs/default.py
Labels: data collection, EGG

#4587 chore: place the build target in spec instead of passing macro
  build_core_rpm.sh
  insights-core.spec
Labels: RPM
